'use client';

import Image from 'next/image';
import { FigureCard, StatCard, DataTable, AblationTable, QRCode } from '@/components';

export default function Poster() {
  return (
    <div className="min-h-screen py-6 px-4">
      <div className="poster-container max-w-7xl mx-auto">

        {/* Header */}
        <header className="bg-[#1e3a5f] text-white p-6">
          <div className="max-w-6xl mx-auto">
            <div className="text-center">
              <p className="text-sm font-sans uppercase tracking-wider text-blue-200 mb-3">
                EACL 2025 · arXiv:2507.00769
              </p>
              <h1 className="text-3xl md:text-4xl font-bold font-sans leading-tight mb-4">
                LitBench: A Benchmark and Dataset for<br />
                Reliable Evaluation of Creative Writing
              </h1>
              <div className="flex flex-wrap justify-center gap-x-4 gap-y-1 text-sm mt-4">
                <span>Daniel Fein<sup>*</sup></span>
                <span>Sebastian Russo<sup>*</sup></span>
                <span>Violet Xiang</span>
                <span>Kabir Jolly</span>
                <span>Rafael Rafailov</span>
                <span>Nick Haber</span>
              </div>
              <p className="text-blue-200 text-sm mt-2 font-sans">
                Stanford University · <sup>*</sup>Equal contribution
              </p>
            </div>
          </div>
        </header>

        {/* Key Stats Bar */}
        <div className="grid grid-cols-4 border-b border-gray-300">
          <StatCard value="2,480" label="Test Pairs" sublabel="Debiased" />
          <StatCard value="43,827" label="Training Pairs" sublabel="Human-labeled" />
          <StatCard value="78%" label="Best Accuracy" sublabel="Trained RM" />
          <StatCard value="73%" label="Best Zero-Shot" sublabel="Claude-3.5" />
        </div>

        {/* Main Content */}
        <main className="p-4">
          <div className="grid grid-cols-1 lg:grid-cols-3 gap-4">

            {/* Column 1 */}
            <div className="space-y-4">

              {/* Abstract */}
              <section className="poster-section">
                <div className="poster-section-header">Abstract</div>
                <div className="p-4">
                  <p className="text-sm leading-relaxed">
                    Evaluating creative writing generated by large language models (LLMs) remains
                    challenging because open-ended narratives lack ground truths. We introduce
                    <strong> LitBench</strong>, the first standardized benchmark for creative writing
                    verification, comprising a held-out test set of <strong>2,480 debiased, human-labeled
                    story comparisons</strong> drawn from Reddit and a <strong>43,827-pair training corpus</strong>.
                    We benchmark zero-shot LLM judges and train reward models, finding that trained
                    models achieve <strong>78% accuracy</strong>, outperforming all off-the-shelf judges.
                  </p>
                </div>
              </section>

              {/* Filtering Pipeline Figure */}
              <FigureCard
                figureNumber={1}
                title="Data Filtering Pipeline"
                caption="Story filtering criteria (left) and story pair debiasing strategies (right) used to construct LitBench."
                expandedContent={
                  <Image
                    src="/figures/filtering-pipeline.png"
                    alt="Filtering Pipeline"
                    width={1200}
                    height={400}
                    className="w-full h-auto"
                  />
                }
              >
                <Image
                  src="/figures/filtering-pipeline.png"
                  alt="Filtering Pipeline"
                  width={600}
                  height={200}
                  className="w-full h-auto"
                />
              </FigureCard>

              {/* Dataset Stats */}
              <section className="poster-section">
                <div className="poster-section-header">Dataset Statistics</div>
                <div className="p-4 space-y-3">
                  <table className="data-table text-sm">
                    <thead>
                      <tr>
                        <th>Statistic</th>
                        <th>Value</th>
                      </tr>
                    </thead>
                    <tbody>
                      <tr>
                        <td>Test comparisons</td>
                        <td className="font-semibold">2,480 pairs</td>
                      </tr>
                      <tr>
                        <td>Training pairs</td>
                        <td className="font-semibold">43,827 pairs</td>
                      </tr>
                      <tr>
                        <td>Unique stories (test)</td>
                        <td className="font-semibold">3,543</td>
                      </tr>
                      <tr>
                        <td>Avg. story length</td>
                        <td className="font-semibold">550 words</td>
                      </tr>
                      <tr>
                        <td>Source</td>
                        <td className="font-semibold">r/WritingPrompts</td>
                      </tr>
                      <tr>
                        <td>Time period</td>
                        <td className="font-semibold">Post-2023</td>
                      </tr>
                    </tbody>
                  </table>
                </div>
              </section>

              {/* Length Debiasing Figure */}
              <FigureCard
                figureNumber={2}
                title="Length Debiasing"
                caption="Distribution of token count differences before (red) and after (purple) frequency-symmetrical debiasing."
                expandedContent={
                  <Image
                    src="/figures/length-debiasing.png"
                    alt="Length Debiasing Distribution"
                    width={1200}
                    height={800}
                    className="w-full h-auto"
                  />
                }
              >
                <Image
                  src="/figures/length-debiasing.png"
                  alt="Length Debiasing Distribution"
                  width={600}
                  height={400}
                  className="w-full h-auto"
                />
              </FigureCard>
            </div>

            {/* Column 2 */}
            <div className="space-y-4">

              {/* Main Results Figure */}
              <FigureCard
                figureNumber={3}
                title="Performance Across RM Types"
                caption="Human agreement (%) for trained reward models (BT, GenRM) and zero-shot judges across model families."
                expandedContent={
                  <div className="space-y-4">
                    <Image
                      src="/figures/main-results.png"
                      alt="Main Results"
                      width={1200}
                      height={600}
                      className="w-full h-auto"
                    />
                    <DataTable />
                  </div>
                }
              >
                <Image
                  src="/figures/main-results.png"
                  alt="Main Results"
                  width={600}
                  height={300}
                  className="w-full h-auto"
                />
              </FigureCard>

              {/* Methodology */}
              <section className="poster-section">
                <div className="poster-section-header">Methodology</div>
                <div className="p-4 space-y-3">
                  <div>
                    <p className="font-semibold font-sans text-sm mb-1">Off-the-Shelf (OTS) Judges</p>
                    <p className="text-sm">
                      Zero-shot evaluation using frontier LLMs (GPT-4, Claude, DeepSeek) and
                      open-source models (Llama, Qwen, Gemma) as pairwise preference judges.
                    </p>
                  </div>

                  <div className="border-t pt-3">
                    <p className="font-semibold font-sans text-sm mb-1">Trained Reward Models</p>
                    <div className="grid grid-cols-2 gap-2 text-sm">
                      <div className="bg-gray-50 border border-gray-200 p-2">
                        <p className="font-semibold">Bradley-Terry (BT)</p>
                        <p className="text-xs text-gray-600">Pairwise preference learning</p>
                      </div>
                      <div className="bg-gray-50 border border-gray-200 p-2">
                        <p className="font-semibold">Generative RM</p>
                        <p className="text-xs text-gray-600">LM-based scoring</p>
                      </div>
                    </div>
                  </div>
                </div>
              </section>

              {/* Scaling Laws Figure */}
              <FigureCard
                figureNumber={4}
                title="Model Scaling Laws"
                caption="Human agreement vs. model size for BT, GenRM, and zero-shot approaches across Llama, Qwen, and Gemma families."
                expandedContent={
                  <Image
                    src="/figures/scaling-laws.png"
                    alt="Model Scaling Laws"
                    width={1200}
                    height={500}
                    className="w-full h-auto"
                  />
                }
              >
                <Image
                  src="/figures/scaling-laws.png"
                  alt="Model Scaling Laws"
                  width={600}
                  height={250}
                  className="w-full h-auto"
                />
              </FigureCard>

              {/* Ablation Study */}
              <section className="poster-section">
                <div className="poster-section-header">Ablation Study</div>
                <div className="p-4">
                  <p className="text-sm mb-3">
                    Impact of debiasing on reward model performance:
                  </p>
                  <AblationTable />
                  <p className="text-xs text-gray-600 mt-3">
                    Debiasing contributes +13pp to final accuracy.
                  </p>
                </div>
              </section>
            </div>

            {/* Column 3 */}
            <div className="space-y-4">

              {/* Feature Importance Figure */}
              <FigureCard
                figureNumber={5}
                title="Feature Importance for Verdict Success"
                caption="Impact of rationale features on model correctness. Plot discussion shows strongest positive effect (+14.8%)."
                expandedContent={
                  <Image
                    src="/figures/feature-importance.png"
                    alt="Feature Importance Heatmap"
                    width={1200}
                    height={500}
                    className="w-full h-auto"
                  />
                }
              >
                <Image
                  src="/figures/feature-importance.png"
                  alt="Feature Importance Heatmap"
                  width={600}
                  height={250}
                  className="w-full h-auto"
                />
              </FigureCard>

              {/* Key Findings */}
              <section className="poster-section">
                <div className="poster-section-header">Key Findings</div>
                <div className="p-4 space-y-3">
                  <div className="finding-box text-sm">
                    <p className="font-semibold mb-1">Trained models outperform zero-shot</p>
                    <p>Both BT and GenRM achieve 78% accuracy, surpassing Claude-3.5 (73%) and GPT-4.1 (71%).</p>
                  </div>
                  <div className="finding-box text-sm">
                    <p className="font-semibold mb-1">Small models struggle</p>
                    <p>Models under 10B parameters achieve only 56-60%—barely above random chance.</p>
                  </div>
                  <div className="finding-box finding-box-accent text-sm">
                    <p className="font-semibold mb-1">Chain-of-thought hurts performance</p>
                    <p>CoT reasoning drops accuracy to 72%, suggesting creative evaluation differs from logical tasks.</p>
                  </div>
                </div>
              </section>

              {/* Ablation Figure */}
              <FigureCard
                figureNumber={6}
                title="Dataset Ablation"
                caption="Left: Training curves for different pairing strategies. Right: Accuracy by response length difference."
                expandedContent={
                  <Image
                    src="/figures/ablation-study.png"
                    alt="Ablation Study"
                    width={1200}
                    height={400}
                    className="w-full h-auto"
                  />
                }
              >
                <Image
                  src="/figures/ablation-study.png"
                  alt="Ablation Study"
                  width={600}
                  height={200}
                  className="w-full h-auto"
                />
              </FigureCard>

              {/* Conclusions */}
              <section className="poster-section">
                <div className="poster-section-header">Conclusions</div>
                <div className="p-4 text-sm space-y-2">
                  <ul className="list-disc list-inside space-y-1">
                    <li>Domain-specific training significantly improves evaluation quality</li>
                    <li>Chain-of-thought reasoning is not universally beneficial</li>
                    <li>Debiased human preferences are essential for training</li>
                    <li>Plot discussion is the strongest predictor of correct verdicts</li>
                  </ul>
                </div>
              </section>

              {/* Resources */}
              <section className="poster-section">
                <div className="poster-section-header">Resources</div>
                <div className="p-4">
                  <div className="flex justify-center gap-6 mb-4 pb-4 border-b border-gray-200">
                    <QRCode url="https://arxiv.org/abs/2507.00769" label="Paper" />
                    <QRCode url="https://huggingface.co/collections/SAA-Lab/litbench-68267b5da3aafe58f9e43461" label="Dataset" />
                    <QRCode url="https://litbench.vercel.app/" label="Demo" />
                  </div>
                  <div className="space-y-1.5 text-sm">
                    <a href="https://arxiv.org/abs/2507.00769" target="_blank" rel="noopener noreferrer" className="resource-link">
                      <span className="font-semibold font-sans">Paper:</span>
                      <span className="text-blue-600">arxiv.org/abs/2507.00769</span>
                    </a>
                    <a href="https://huggingface.co/collections/SAA-Lab/litbench-68267b5da3aafe58f9e43461" target="_blank" rel="noopener noreferrer" className="resource-link">
                      <span className="font-semibold font-sans">Dataset:</span>
                      <span className="text-blue-600">HuggingFace/SAA-Lab/litbench</span>
                    </a>
                  </div>
                </div>
              </section>
            </div>
          </div>
        </main>

        {/* Footer */}
        <footer className="bg-gray-100 px-6 py-4 border-t border-gray-300">
          <div className="flex items-center justify-between text-sm text-gray-600">
            <div>
              <span className="font-semibold font-sans">Stanford University</span>
              <span className="mx-2">·</span>
              <span>SAA Lab</span>
            </div>
            <div className="text-xs">
              Contact: litbench@stanford.edu · Click figures to enlarge
            </div>
          </div>
        </footer>
      </div>
    </div>
  );
}
